proxy_location: EveryNode

http_options:
  host: 0.0.0.0
  port: 8000

applications:
- name: default
  import_path: main:app_ingress
  route_prefix: /
  deployments:
  - name: IngressServer
  - name: DeployWhisper
  - name: DeployQwen
